#!/bin/bash

# Vercel環境変数をconfig.jsに書き込む
cat > config.js <<CONFIGEOF
// Auto-generated by build.sh from Vercel environment variables
const LIFF_ID = '${LIFF_ID}';
const GAS_BASE_URL = '${GAS_BASE_URL}';
CONFIGEOF

echo "config.js generated with environment variables"
cat config.js
