#!/bin/bash

# 依存関係インストール
npm install

# TypeScriptビルド
npm run build

# Vercel環境変数をconfig.jsに書き込む
cat > config.js <<CONFIGEOF
// Auto-generated by build.sh from Vercel environment variables
const LIFF_ID = '${LIFF_ID}';
const GAS_BASE_URL = '${GAS_BASE_URL}';
CONFIGEOF

echo "config.js generated with environment variables"
cat config.js

# Vercel Build Output API v3に対応
mkdir -p .vercel/output/static
cp index.html .vercel/output/static/
cp config.js .vercel/output/static/
cp -r dist .vercel/output/static/
echo '{"version": 3}' > .vercel/output/config.json

echo "Files copied to .vercel/output/static"
ls -la .vercel/output/static
